### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by trang1618** [ameliatlm/missing-data-4ce#1]
- [x] update lab value bounds
- [x] aggregate summary statistics from sites (data frames in addition to plots), save to results (maybe `.csv` files)
- [x] binning for heatmap
- [x] add readme
- [x] calculate more missingness statistics (number of patients, etc.)
- [ ] ...

**Comment by trang1618** [comment]
Completed as of 2020-11-10 in https://github.com/ameliatlm/missing-data-4ce/commit/35836f2f21d477d68c0977555548f00c87cde64a.
